-- =====================================================================
-- UniSphere / EduHub — demo seed.sql
-- =====================================================================
--
-- Idempotent. Safe to re-run. Provisions:
--   * 1 department + 1 program (find-or-create)
--   * 15 skills (find-or-create)
--   * 5 teachers  (instructor rows linked to auth.users that already exist)
--   * manual_courses — teachers who already own a REAL course (fetched live
--     by tools/seed.py) keep it as-is; only teachers with none get 2 demo
--     courses each
--   * 25 students (linked to auth.users that already exist)
--   * enrollments (round-robin across the real + demo course pool, so a
--     teacher's real pre-existing course gets students too)
--   * 5–10 course_invite rows
--   * 2 attendance sessions + records, and a midterm/final exam + marks,
--     per course that has enrolled students
--   * 10 projects (skills + author)
--   * 8 certificates (skills)
--   * 10 research papers (5 teacher + 5 student)
--   * 25 advisor rows (one per student)
--   * 3 group chat rooms (with room codes) with members + a few messages
--   * 1 pending chat_request
--   * 8 sample notifications
--
-- Required environment:
--     - All schema migrations applied (schema.sql + achievements_schema.sql
--       + classes_exam_schema.sql + classes_resources_schema.sql
--       + chatroom.sql + chat_requests.sql + notice_board_schema.sql
--       + profile_feature.sql + classes_migration_2026.sql + fix_*.sql).
--     - Auth users exist. tools/seed.py creates them via the service-role
--       Admin API (auth.admin.create_user) and the handle_new_user trigger
--       auto-creates profiles. The IDs are emitted to /tmp/seed_ids.json.
--
-- Usage:
--     psql "$SUPABASE_DB_URL" \
--         -v seed_ids_json="$(cat /tmp/seed_ids.json)" \
--         -v ON_ERROR_STOP=1 \
--         -f Database/seed.sql
-- =====================================================================

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------
-- 0. Load the JSON map of auth.users IDs generated by tools/seed.py
-- ---------------------------------------------------------------------
-- psql :'seed_ids_json' substitutes the JSON string as a psql literal.
-- We wrap it in a DO block that validates JSON and stashes it in
-- current_setting('seed.ids', true) so subsequent blocks can read it.
DO $$
DECLARE
    v_json text := current_setting('seed.ids', true);
    v_parsed jsonb;
BEGIN
    IF v_json IS NULL OR v_json = '' THEN
        RAISE EXCEPTION
            'seed.ids is empty. Run: tools/seed.py --out /tmp/seed_ids.json';
    END IF;

    BEGIN
        v_parsed := v_json::jsonb;
    EXCEPTION WHEN others THEN
        RAISE EXCEPTION 'seed.ids is not valid JSON: %', SQLERRM;
    END;

    PERFORM set_config('seed.ids', v_parsed::text, false);
    RAISE NOTICE 'seed.ids loaded: % teachers, % students',
        jsonb_array_length(v_parsed->'teachers'),
        jsonb_array_length(v_parsed->'students');
END $$;

-- =====================================================================
-- A. Reference data (idempotent)
-- =====================================================================

-- 1 department
INSERT INTO public.department (dept_name, dept_code, is_active)
VALUES ('Computer Science and Engineering', 'CSE', TRUE)
ON CONFLICT (dept_code) DO NOTHING;

-- 1 program under the CSE department (matches the DU CSE curriculum: 150 total credits)
-- Rename a previously-seeded 'BSC-CSE' program code to the correct 'CSE-BSC', if present.
UPDATE public.program SET program_code = 'CSE-BSC' WHERE program_code = 'BSC-CSE';

INSERT INTO public.program (dept_id, program_name, program_code, degree_level,
                            duration_years, total_credits, is_active)
SELECT d.dept_id,
       'Bachelor of Science in Computer Science and Engineering',
       'CSE-BSC',
       'Bachelor',
       4.0,
       150,
       TRUE
FROM public.department d WHERE d.dept_code = 'CSE'
ON CONFLICT (program_code) DO NOTHING;

UPDATE public.program SET total_credits = 150 WHERE program_code = 'CSE-BSC';

-- 15 skills
INSERT INTO public.skill (skill_name, category) VALUES
    ('Python',            'Programming'),
    ('Java',              'Programming'),
    ('C++',               'Programming'),
    ('JavaScript',        'Programming'),
    ('TypeScript',        'Programming'),
    ('SQL',               'Database'),
    ('React',             'Frontend'),
    ('Next.js',           'Frontend'),
    ('Node.js',           'Backend'),
    ('FastAPI',           'Backend'),
    ('Docker',            'DevOps'),
    ('PostgreSQL',        'Database'),
    ('Machine Learning',  'AI/ML'),
    ('Deep Learning',     'AI/ML'),
    ('Data Structures',   'CS Core')
ON CONFLICT (skill_name) DO NOTHING;


-- =====================================================================
-- B. Teachers → instructor rows (idempotent via employee_id)
-- =====================================================================
DO $$
DECLARE
    v_dept_id  INT;
    v_emp_id   TEXT;
    v_uid      UUID;
    v_fname    TEXT;
    v_lname    TEXT;
    v_gender   public.gender_val;
    v_dob      DATE;
    v_phone    TEXT;
    v_desig    public.designation_val;
    v_spec     TEXT;
    v_office   TEXT;
    v_bio      TEXT;
    v_teacher  jsonb;
    v_instr_id INT;
BEGIN
    SELECT dept_id INTO v_dept_id FROM public.department WHERE dept_code = 'CSE';
    IF v_dept_id IS NULL THEN
        RAISE EXCEPTION 'CSE department missing — section A must run first';
    END IF;

    FOR v_teacher IN
        SELECT * FROM jsonb_array_elements(
            current_setting('seed.ids', true)::jsonb->'teachers'
        )
    LOOP
        v_uid    := (v_teacher->>'uid')::UUID;
        v_fname  := v_teacher->>'first_name';
        v_lname  := v_teacher->>'last_name';
        v_gender := (v_teacher->>'gender')::public.gender_val;
        v_dob    := (v_teacher->>'dob')::DATE;
        v_phone  := v_teacher->>'phone';
        v_desig  := (v_teacher->>'designation')::public.designation_val;
        v_spec   := v_teacher->>'specialization';
        v_office := v_teacher->>'office_location';
        v_bio    := v_teacher->>'bio';
        v_emp_id := v_teacher->>'employee_id';

        -- hire_date between 1 and 10 years ago
        INSERT INTO public.instructor (
            profile_id, dept_id, first_name, last_name, gender, date_of_birth,
            phone, employee_id, hire_date, designation, specialization,
            office_location, bio, is_active
        )
        VALUES (
            v_uid, v_dept_id, v_fname, v_lname, v_gender, v_dob,
            v_phone, v_emp_id,
            CURRENT_DATE - (INTERVAL '1 year' + (RANDOM() * INTERVAL '9 years')),
            v_desig, v_spec, v_office, v_bio, TRUE
        )
        ON CONFLICT (employee_id) DO NOTHING
        RETURNING instructor_id INTO v_instr_id;

        IF v_instr_id IS NULL THEN
            SELECT instructor_id INTO v_instr_id
            FROM public.instructor WHERE employee_id = v_emp_id;
        END IF;

        UPDATE public.profiles
        SET instructor_id = v_instr_id,
            first_name    = v_fname,
            last_name     = v_lname,
            phone         = v_phone
        WHERE id = v_uid;
    END LOOP;
END $$;


-- =====================================================================
-- C. Manual courses (2 per teacher, 10 total)
-- =====================================================================
-- Uses a PL/pgSQL counter variable so each teacher gets courses 2*t and 2*t+1.
DO $$
DECLARE
    v_emp_id   TEXT;
    v_instr_id INT;
    v_uid      UUID;
    v_i        INT;
    v_t_idx    INT := 0;
    v_course   jsonb;
    v_teacher  jsonb;
    -- Real DU CSE curriculum courses (Database/Curriculum (1).pdf), 2 per teacher:
    -- EMP-101 Algorithms/ToC, EMP-102 ML/AI, EMP-103 Networks, EMP-104 DB/DSA, EMP-105 SE/Web
    v_courses jsonb := '[
        {"name":"Theory of Computation","code":"CSE3207","credits":3.0,"sem":"Fall 2025","year":"2025-2026","snum":6,"enroll":"CSE3207A"},
        {"name":"Design and Analysis of Algorithms","code":"CSE2203","credits":3.0,"sem":"Spring 2026","year":"2025-2026","snum":4,"enroll":"CSE2203A"},
        {"name":"Machine Learning","code":"CSE4101","credits":3.0,"sem":"Fall 2025","year":"2025-2026","snum":7,"enroll":"CSE4101A"},
        {"name":"Artificial Intelligence","code":"CSE3203","credits":3.0,"sem":"Fall 2025","year":"2025-2026","snum":6,"enroll":"CSE3203A"},
        {"name":"Computer Network","code":"CSE3201","credits":3.0,"sem":"Fall 2025","year":"2025-2026","snum":6,"enroll":"CSE3201A"},
        {"name":"Data and Telecommunication","code":"CSE2109","credits":3.0,"sem":"Spring 2026","year":"2025-2026","snum":3,"enroll":"CSE2109A"},
        {"name":"Database Management System","code":"CSE2201","credits":3.0,"sem":"Spring 2026","year":"2025-2026","snum":4,"enroll":"CSE2201A"},
        {"name":"Data Structures and Algorithms","code":"CSE2101","credits":3.0,"sem":"Spring 2026","year":"2025-2026","snum":3,"enroll":"CSE2101A"},
        {"name":"Software Engineering","code":"CSE3101","credits":3.0,"sem":"Fall 2025","year":"2025-2026","snum":5,"enroll":"CSE3101A"},
        {"name":"Web Engineering and Technology","code":"CSE3103","credits":3.0,"sem":"Fall 2025","year":"2025-2026","snum":5,"enroll":"CSE3103A"}
    ]'::jsonb;
    v_dept_id INT;
BEGIN
    SELECT dept_id INTO v_dept_id FROM public.department WHERE dept_code = 'CSE';

    v_t_idx := 0;
    FOR v_teacher IN
        SELECT * FROM jsonb_array_elements(
            current_setting('seed.ids', true)::jsonb->'teachers'
        )
    LOOP
        v_emp_id   := v_teacher->>'employee_id';
        v_instr_id := NULL;
        SELECT instructor_id INTO v_instr_id
        FROM public.instructor WHERE employee_id = v_emp_id;

        IF v_instr_id IS NULL THEN
            RAISE NOTICE 'Skipping teacher % — no instructor row found', v_emp_id;
            v_t_idx := v_t_idx + 1;
            CONTINUE;
        END IF;

        -- Skip demo-course creation for teachers who already own real
        -- course(s), fetched live by tools/seed.py into existing_enroll_codes.
        -- Students should be enrolled into that real course instead (Section E).
        IF jsonb_array_length(COALESCE(v_teacher->'existing_enroll_codes', '[]'::jsonb)) > 0 THEN
            RAISE NOTICE 'Teacher % already has real course(s) — skipping demo courses', v_emp_id;
            v_t_idx := v_t_idx + 1;
            CONTINUE;
        END IF;

        FOR v_i IN 0..1 LOOP
            v_course := v_courses -> (v_t_idx * 2 + v_i);

            INSERT INTO public.manual_course (
                instructor_id, dept_id, course_name, course_code, description,
                credit_hours, enroll_code, semester, academic_year,
                semester_number, is_active
            )
            VALUES (
                v_instr_id, v_dept_id,
                v_course->>'name',
                v_course->>'code',
                'Demo course for ' || (v_teacher->>'first_name') || ' ' || (v_teacher->>'last_name'),
                (v_course->>'credits')::NUMERIC,
                v_course->>'enroll',
                v_course->>'sem',
                v_course->>'year',
                (v_course->>'snum')::SMALLINT,
                TRUE
            )
            ON CONFLICT (enroll_code) DO NOTHING;
        END LOOP;

        v_t_idx := v_t_idx + 1;
    END LOOP;
END $$;


-- =====================================================================
-- D. Students → student rows (idempotent via student_roll)
-- =====================================================================
DO $$
DECLARE
    v_program_id INT;
    v_student    jsonb;
    v_uid        UUID;
    v_fname      TEXT;
    v_lname      TEXT;
    v_gender     public.gender_val;
    v_dob        DATE;
    v_phone      TEXT;
    v_roll       TEXT;
    v_batch      SMALLINT;
    v_sem        SMALLINT;
    v_address    TEXT;
    v_cgpa       NUMERIC(4,2);
    v_credits    SMALLINT;
    v_student_id INT;
BEGIN
    SELECT program_id INTO v_program_id FROM public.program WHERE program_code = 'CSE-BSC';
    IF v_program_id IS NULL THEN
        RAISE EXCEPTION 'CSE-BSC program missing — section A must run first';
    END IF;

    FOR v_student IN
        SELECT * FROM jsonb_array_elements(
            current_setting('seed.ids', true)::jsonb->'students'
        )
    LOOP
        v_uid     := (v_student->>'uid')::UUID;
        v_fname   := v_student->>'first_name';
        v_lname   := v_student->>'last_name';
        v_gender  := (v_student->>'gender')::public.gender_val;
        v_dob     := (v_student->>'dob')::DATE;
        v_phone   := v_student->>'phone';
        v_roll    := v_student->>'roll';
        v_batch   := (v_student->>'batch_year')::SMALLINT;
        v_sem     := (v_student->>'current_semester')::SMALLINT;
        v_address := v_student->>'address';

        -- CGPA and credits depend on semester # to feel realistic
        v_cgpa    := ROUND((2.50 + RANDOM() * 1.45)::NUMERIC, 2);
        v_credits := ((v_sem - 1) / 2) * 20 + 18 + (RANDOM() * 4)::SMALLINT;

        INSERT INTO public.student (
            profile_id, program_id, first_name, last_name, gender, date_of_birth,
            phone, address, student_roll, batch_year, current_semester,
            cgpa, total_credits, emergency_contact_name, emergency_contact_phone,
            is_active
        )
        VALUES (
            v_uid, v_program_id, v_fname, v_lname, v_gender, v_dob,
            v_phone, v_address, v_roll, v_batch, v_sem,
            v_cgpa, v_credits,
            'Guardian ' || v_fname,
            '+88019' || lpad((10000000 + (RANDOM() * 89999999)::INT)::TEXT, 8, '0'),
            TRUE
        )
        ON CONFLICT (student_roll) DO NOTHING
        RETURNING student_id INTO v_student_id;

        IF v_student_id IS NULL THEN
            SELECT student_id INTO v_student_id
            FROM public.student WHERE student_roll = v_roll;
        END IF;

        UPDATE public.profiles
        SET student_id = v_student_id,
            first_name = v_fname,
            last_name  = v_lname,
            phone      = v_phone
        WHERE id = v_uid;
    END LOOP;
END $$;


-- =====================================================================
-- E. Enrollments — distribute 25 students across the entire course pool
-- =====================================================================
-- The pool is every active manual_course in the DB — any teacher's real,
-- already-created course(s) (however they were made, demo teacher or not)
-- plus the 10 curriculum-based demo courses from Section C. This ensures a
-- real pre-existing course (e.g. one made through the app UI) also gets
-- students, matching "teacher already created a course, add students to it."
-- Round-robin: student i gets pool[i % n] and pool[(i+2) % n], so each
-- course gets students and each student gets 2 courses.
DO $$
DECLARE
    v_courses  INT[];
    v_students INT[];
    v_idx      INT;
    v_student_id INT;
    v_course_id  INT;
BEGIN
    SELECT COALESCE(array_agg(manual_course_id ORDER BY manual_course_id), '{}')
      INTO v_courses
    FROM public.manual_course
    WHERE is_active;

    SELECT COALESCE(array_agg(student_id ORDER BY student_id), '{}')
      INTO v_students
    FROM public.student
    WHERE student_roll BETWEEN '2023715001' AND '2023715025';

    IF array_length(v_courses, 1) IS NULL OR array_length(v_students, 1) IS NULL THEN
        RAISE NOTICE 'No fresh courses or students found — skipping enrollment';
        RETURN;
    END IF;

    FOR v_idx IN 1..array_length(v_students, 1) LOOP
        v_student_id := v_students[v_idx];
        v_course_id  := v_courses[((v_idx - 1) % array_length(v_courses, 1)) + 1];

        INSERT INTO public.manual_enrollment (manual_course_id, student_id, is_active)
        VALUES (v_course_id, v_student_id, TRUE)
        ON CONFLICT (manual_course_id, student_id) DO NOTHING;

        v_course_id  := v_courses[((v_idx + 1) % array_length(v_courses, 1)) + 1];
        INSERT INTO public.manual_enrollment (manual_course_id, student_id, is_active)
        VALUES (v_course_id, v_student_id, TRUE)
        ON CONFLICT (manual_course_id, student_id) DO NOTHING;
    END LOOP;
END $$;


-- =====================================================================
-- E2. Classes: attendance sessions/records + exams/marks per course
-- =====================================================================
-- For every course that has enrolled students (real or demo), create a
-- couple of attendance sessions with per-student records, plus a midterm
-- and final exam with per-student marks — so teacher dashboards ("classes")
-- have real data to show.
DO $$
DECLARE
    v_course       RECORD;
    v_student_id   INT;
    v_session_id   INT;
    v_exam_id      INT;
    v_marks        NUMERIC;
    v_total        NUMERIC;
    v_grade        TEXT;
    v_points       NUMERIC;
    v_created_by   UUID;
    v_topics       TEXT[] := ARRAY['Introduction & Overview','Core Concepts','Problem Solving Session'];
    v_i            INT;
BEGIN
    FOR v_course IN
        SELECT mc.manual_course_id, mc.course_name, mc.credit_hours, mc.semester,
               mc.academic_year, i.profile_id AS instructor_profile_id
        FROM public.manual_course mc
        JOIN public.instructor i ON i.instructor_id = mc.instructor_id
        WHERE EXISTS (
            SELECT 1 FROM public.manual_enrollment me
            WHERE me.manual_course_id = mc.manual_course_id AND me.is_active
        )
    LOOP
        v_created_by := v_course.instructor_profile_id;
        IF v_created_by IS NULL THEN CONTINUE; END IF;

        -- Idempotency: skip courses that already have seeded sessions/exams
        IF EXISTS (SELECT 1 FROM public.attendance_session s WHERE s.manual_course_id = v_course.manual_course_id)
           OR EXISTS (SELECT 1 FROM public.exam e WHERE e.manual_course_id = v_course.manual_course_id) THEN
            CONTINUE;
        END IF;

        -- 2 attendance sessions
        FOR v_i IN 1..2 LOOP
            INSERT INTO public.attendance_session (
                manual_course_id, instructor_id, session_date, session_title, topic
            )
            SELECT v_course.manual_course_id, mc.instructor_id,
                   CURRENT_DATE - (7 * (3 - v_i)),
                   'Class Session ' || v_i,
                   v_topics[v_i]
            FROM public.manual_course mc WHERE mc.manual_course_id = v_course.manual_course_id
            RETURNING session_id INTO v_session_id;

            INSERT INTO public.attendance_record (session_id, student_id, status)
            SELECT v_session_id, me.student_id,
                   CASE WHEN RANDOM() < 0.85 THEN 'Present'
                        WHEN RANDOM() < 0.6 THEN 'Late'
                        ELSE 'Absent' END
            FROM public.manual_enrollment me
            WHERE me.manual_course_id = v_course.manual_course_id AND me.is_active;
        END LOOP;

        -- Midterm + Final exams
        FOR v_i IN 1..2 LOOP
            v_total := CASE WHEN v_i = 1 THEN 30 ELSE 50 END;
            INSERT INTO public.exam (
                manual_course_id, exam_name, exam_type, total_marks, credit_hours,
                exam_date, semester, academic_year, description, is_published, created_by
            )
            VALUES (
                v_course.manual_course_id,
                v_course.course_name || CASE WHEN v_i = 1 THEN ' - Midterm' ELSE ' - Final' END,
                CASE WHEN v_i = 1 THEN 'Midterm' ELSE 'Final' END,
                v_total, v_course.credit_hours,
                CURRENT_DATE - (30 * (3 - v_i)),
                v_course.semester, v_course.academic_year,
                'Demo exam for ' || v_course.course_name,
                TRUE, v_created_by
            )
            RETURNING exam_id INTO v_exam_id;

            FOR v_student_id IN
                SELECT me.student_id FROM public.manual_enrollment me
                WHERE me.manual_course_id = v_course.manual_course_id AND me.is_active
            LOOP
                v_marks := ROUND((v_total * (0.60 + RANDOM() * 0.35))::NUMERIC, 2);
                v_grade := CASE
                    WHEN v_marks >= v_total * 0.90 THEN 'A+'
                    WHEN v_marks >= v_total * 0.80 THEN 'A'
                    WHEN v_marks >= v_total * 0.70 THEN 'A-'
                    WHEN v_marks >= v_total * 0.60 THEN 'B'
                    ELSE 'C'
                END;
                v_points := CASE v_grade
                    WHEN 'A+' THEN 4.00 WHEN 'A' THEN 3.75 WHEN 'A-' THEN 3.50
                    WHEN 'B' THEN 3.00 ELSE 2.50
                END;

                INSERT INTO public.exam_mark (
                    exam_id, student_id, marks_obtained, grade, grade_points, entered_by
                )
                VALUES (v_exam_id, v_student_id, v_marks, v_grade, v_points, v_created_by)
                ON CONFLICT (exam_id, student_id) DO NOTHING;
            END LOOP;
        END LOOP;
    END LOOP;
END $$;


-- =====================================================================
-- F. Teacher-initiated course_invites (8 accepted + 2 pending)
-- =====================================================================
INSERT INTO public.course_invite (manual_course_id, student_id, invited_by, status, message)
SELECT me.manual_course_id, me.student_id, mc.instructor_id, 'accepted',
       'Welcome to the course!'
FROM public.manual_enrollment me
JOIN public.manual_course mc ON mc.manual_course_id = me.manual_course_id
WHERE me.student_id IN (
    SELECT student_id FROM public.student
    WHERE student_roll BETWEEN '2023715001' AND '2023715008'
)
ON CONFLICT (manual_course_id, student_id) DO NOTHING;

INSERT INTO public.course_invite (manual_course_id, student_id, invited_by, status, message)
SELECT mc.manual_course_id, s.student_id, mc.instructor_id, 'pending',
       'You are invited to join this lab.'
FROM public.student s
CROSS JOIN LATERAL (
    SELECT manual_course_id, instructor_id
    FROM public.manual_course
    WHERE enroll_code IN ('CSE4101A','CSE3203A')
    ORDER BY manual_course_id
    LIMIT 1
) mc
WHERE s.student_roll IN ('2023715024','2023715025')
ON CONFLICT (manual_course_id, student_id) DO NOTHING;


-- =====================================================================
-- G. Achievements (projects, certificates, research papers)
-- =====================================================================

-- ---- G.1 Projects (10 rows owned by 6 students) ----
DO $$
DECLARE
    v_projects jsonb := '[
        {"roll":"2023715001","title":"Smart Campus Event Finder","desc":"React Native app surfacing campus events via Supabase real-time.","year":2024,"month":6,"end_year":2024,"end_month":11,"github":"https://github.com/demo/campus-finder","demo":"https://campus-finder.demo.app","skills":["React","TypeScript","PostgreSQL"]},
        {"roll":"2023715002","title":"Bangla Handwritten Digit Recognition","desc":"CNN trained on NumtaDB achieving 97.4% accuracy.","year":2024,"month":1,"end_year":2024,"end_month":5,"github":"https://github.com/demo/bangla-digits","demo":"","skills":["Python","Deep Learning"]},
        {"roll":"2023715003","title":"DSA Visualizer","desc":"Interactive Next.js app for sorting and graph algorithms.","year":2023,"month":9,"end_year":2024,"end_month":3,"github":"https://github.com/demo/dsa-viz","demo":"https://dsa-viz.demo.app","skills":["Next.js","TypeScript","Data Structures"]},
        {"roll":"2023715004","title":"Library Seat Reservation API","desc":"FastAPI + Postgres with row-level locking for seat booking.","year":2024,"month":2,"end_year":2024,"end_month":7,"github":"https://github.com/demo/library-api","demo":"","skills":["FastAPI","Python","PostgreSQL"]},
        {"roll":"2023715005","title":"CUET Online Judge Mirror","desc":"Self-hosted judge0 + Next.js clone for departmental use.","year":2023,"month":6,"end_year":2024,"end_month":2,"github":"https://github.com/demo/judge-mirror","demo":"https://judge.demo.app","skills":["Docker","Node.js","React"]},
        {"roll":"2023715006","title":"Exam Seating Arrangement Tool","desc":"Constraint-based seating generator using OR-tools.","year":2024,"month":3,"end_year":2024,"end_month":8,"github":"https://github.com/demo/seating","demo":"","skills":["Python"]},
        {"roll":"2023715007","title":"Real-time Chat Server","desc":"WebSocket chat server with Supabase realtime replication.","year":2024,"month":4,"end_year":null,"end_month":null,"is_current":true,"github":"https://github.com/demo/chat-server","demo":"https://chat.demo.app","skills":["Node.js","Docker"]},
        {"roll":"2023715008","title":"Personal Finance Tracker","desc":"Mobile-first PWA tracking daily expenses with charts.","year":2023,"month":11,"end_year":2024,"end_month":4,"github":"https://github.com/demo/finance","demo":"https://finance.demo.app","skills":["React","JavaScript"]},
        {"roll":"2023715002","title":"Notes Summariser","desc":"Transformer-based PDF summarizer with section-wise quizzes.","year":2024,"month":7,"end_year":null,"end_month":null,"is_current":true,"github":"https://github.com/demo/summariser","demo":"","skills":["Python","Machine Learning"]},
        {"roll":"2023715003","title":"Alumni Network Platform","desc":"Community platform for DU CSE alumni with job board.","year":2023,"month":1,"end_year":2023,"end_month":8,"github":"https://github.com/demo/alumni","demo":"https://alumni.demo.app","skills":["Next.js","Node.js","PostgreSQL"]}
    ]'::jsonb;
    v_proj     jsonb;
    v_uid      UUID;
    v_skill_id INT;
    v_proj_id  INT;
BEGIN
    FOR v_proj IN SELECT * FROM jsonb_array_elements(v_projects) LOOP
        SELECT profile_id INTO v_uid
        FROM public.student s
        WHERE s.student_roll = (v_proj->>'roll');

        IF v_uid IS NULL THEN CONTINUE; END IF;

        INSERT INTO public.project (
            user_id, title, description, github_url, live_demo_url,
            start_month, start_year, end_month, end_year, is_current,
            associated_with, is_published
        )
        VALUES (
            v_uid, v_proj->>'title', v_proj->>'desc',
            NULLIF(v_proj->>'github',''), NULLIF(v_proj->>'demo',''),
            (v_proj->>'month')::SMALLINT, (v_proj->>'year')::SMALLINT,
            NULLIF(v_proj->>'end_month','')::SMALLINT,
            NULLIF(v_proj->>'end_year','')::SMALLINT,
            COALESCE((v_proj->>'is_current')::BOOLEAN, FALSE),
            'CSE Department Demo', TRUE
        )
        RETURNING project_id INTO v_proj_id;

        FOR v_skill_id IN
            SELECT skill_id FROM public.skill
            WHERE skill_name IN (
                SELECT jsonb_array_elements_text(v_proj->'skills')
            )
        LOOP
            INSERT INTO public.project_skill (project_id, skill_id)
            VALUES (v_proj_id, v_skill_id)
            ON CONFLICT DO NOTHING;
        END LOOP;
    END LOOP;
END $$;

-- ---- G.2 Certificates (8 rows distributed across students) ----
DO $$
DECLARE
    v_certs jsonb := '[
        {"roll":"2023715001","name":"AWS Cloud Practitioner","org":"Amazon Web Services","yr":2024,"cred":"AWS-CCP-2024-DEMO","url":"https://aws.amazon.com/verification/DEMO","skill":"Docker"},
        {"roll":"2023715002","name":"Deep Learning Specialization","org":"Coursera (deeplearning.ai)","yr":2024,"cred":"DL-CRS-2024-DEMO","url":"https://coursera.org/verify/DEMO","skill":"Deep Learning"},
        {"roll":"2023715003","name":"Meta Front-End Developer","org":"Coursera (Meta)","yr":2024,"cred":"META-FE-2024-DEMO","url":"https://coursera.org/verify/DEMO","skill":"React"},
        {"roll":"2023715004","name":"HackerRank SQL Intermediate","org":"HackerRank","yr":2023,"cred":"HR-SQL-2023-DEMO","url":"https://hackerrank.com/cert/DEMO","skill":"SQL"},
        {"roll":"2023715005","name":"Docker Essentials","org":"Cognitive Class","yr":2024,"cred":"DOCKER-2024-DEMO","url":"https://cognitiveclass.ai/cert/DEMO","skill":"Docker"},
        {"roll":"2023715006","name":"Google Data Analytics","org":"Coursera (Google)","yr":2023,"cred":"GDA-2023-DEMO","url":"https://coursera.org/verify/DEMO","skill":"Python"},
        {"roll":"2023715007","name":"React Basics","org":"HackerRank","yr":2024,"cred":"HR-RCT-2024-DEMO","url":"https://hackerrank.com/cert/DEMO","skill":"React"},
        {"roll":"2023715008","name":"Microsoft Azure Fundamentals","org":"Microsoft","yr":2024,"cred":"AZ-900-2024-DEMO","url":"https://learn.microsoft.com/verify/DEMO","skill":"Docker"}
    ]'::jsonb;
    v_c       jsonb;
    v_uid     UUID;
    v_skill_id INT;
    v_cert_id INT;
BEGIN
    FOR v_c IN SELECT * FROM jsonb_array_elements(v_certs) LOOP
        SELECT profile_id INTO v_uid FROM public.student WHERE student_roll = (v_c->>'roll');
        IF v_uid IS NULL THEN CONTINUE; END IF;

        INSERT INTO public.certificate (
            user_id, cert_name, issuing_org, issue_year, credential_id, credential_url
        )
        VALUES (
            v_uid, v_c->>'name', v_c->>'org', (v_c->>'yr')::SMALLINT,
            v_c->>'cred', v_c->>'url'
        )
        RETURNING certificate_id INTO v_cert_id;

        SELECT skill_id INTO v_skill_id FROM public.skill WHERE skill_name = (v_c->>'skill');
        IF v_skill_id IS NOT NULL THEN
            INSERT INTO public.certificate_skill (certificate_id, skill_id)
            VALUES (v_cert_id, v_skill_id)
            ON CONFLICT DO NOTHING;
        END IF;
    END LOOP;
END $$;

-- ---- G.3 Research papers (5 teacher + 5 student) ----
DO $$
DECLARE
    v_papers jsonb := '[
        {"role":"teacher","email":"teacher1@demo.eduhub","title":"A Survey of Graph Neural Networks in 2024","journal":"ACM Computing Surveys","yr":2024,"doi":"10.0000/demo.gnn.2024"},
        {"role":"teacher","email":"teacher2@demo.eduhub","title":"Transformer Compression for Low-Resource Languages","journal":"EMNLP Findings","yr":2024,"doi":"10.0000/demo.transformer.2024"},
        {"role":"teacher","email":"teacher3@demo.eduhub","title":"Latency-Aware Task Scheduling in 5G Edge","conference":"IEEE INFOCOM","yr":2024,"doi":"10.0000/demo.5g.2024"},
        {"role":"teacher","email":"teacher4@demo.eduhub","title":"Learned Index Structures for In-Memory Stores","journal":"VLDB","yr":2024,"doi":"10.0000/demo.index.2024"},
        {"role":"teacher","email":"teacher5@demo.eduhub","title":"Cognitive Load in Mobile Health Apps","conference":"CHI","yr":2024,"doi":"10.0000/demo.chi.2024"},
        {"role":"student","roll":"2023715001","title":"Undergraduate Honors Thesis: Smart Campus Finder","journal":"DU CSEDU","yr":2024,"doi":""},
        {"role":"student","roll":"2023715002","title":"Bangla Digit Recognition: A Comparative Study","conference":"ICBSLP","yr":2024,"doi":"10.0000/demo.bangla.2024"},
        {"role":"student","roll":"2023715003","title":"Visualizing Linked List Operations in WebGL","journal":"Demo Journal","yr":2023,"doi":""},
        {"role":"student","roll":"2023715004","title":"Concurrency Patterns in FastAPI + Postgres","conference":"PyCon Asia","yr":2024,"doi":"10.0000/demo.pycon.2024"},
        {"role":"student","roll":"2023715005","title":"Online Judge Auto-Grader for C++","journal":"Demo Journal","yr":2023,"doi":""}
    ]'::jsonb;
    v_p       jsonb;
    v_uid     UUID;
    v_paper_id INT;
    v_full_name TEXT;
BEGIN
    FOR v_p IN SELECT * FROM jsonb_array_elements(v_papers) LOOP
        IF v_p->>'role' = 'teacher' THEN
            SELECT i.profile_id INTO v_uid
            FROM public.instructor i
            JOIN public.profiles pr ON pr.id = i.profile_id
            JOIN auth.users au ON au.id = pr.id
            WHERE au.email = (v_p->>'email')
            LIMIT 1;
        ELSE
            SELECT profile_id INTO v_uid
            FROM public.student WHERE student_roll = (v_p->>'roll');
        END IF;

        IF v_uid IS NULL THEN CONTINUE; END IF;

        INSERT INTO public.research_paper (
            user_id, title, abstract, journal_name, conference_name, doi,
            publish_year, citation_count, is_published
        )
        VALUES (
            v_uid, v_p->>'title',
            'Demo abstract for ' || (v_p->>'title'),
            NULLIF(v_p->>'journal',''),
            NULLIF(v_p->>'conference',''),
            NULLIF(v_p->>'doi',''),
            (v_p->>'yr')::SMALLINT,
            (RANDOM() * 25)::INT,
            TRUE
        )
        RETURNING paper_id INTO v_paper_id;

        SELECT first_name || ' ' || last_name INTO v_full_name
        FROM public.profiles WHERE id = v_uid;

        INSERT INTO public.research_paper_author (paper_id, user_id, author_name, author_order, is_corresponding)
        VALUES (v_paper_id, v_uid, v_full_name, 1, TRUE)
        ON CONFLICT (paper_id, author_order) DO NOTHING;
    END LOOP;
END $$;


-- =====================================================================
-- H. Advisor links (one per student, round-robin across 5 teachers)
-- =====================================================================
INSERT INTO public.advisor (student_id, advisor_instructor_id)
SELECT s.student_id,
       (ARRAY(SELECT instructor_id FROM public.instructor
              ORDER BY instructor_id))[((s.student_id - 1) % 5) + 1]
FROM public.student s
WHERE s.student_roll BETWEEN '2023715001' AND '2023715025'
ON CONFLICT (student_id) DO NOTHING;


-- =====================================================================
-- I. Group chat rooms (3 rooms + members + messages + 1 chat_request)
-- =====================================================================
DO $$
DECLARE
    v_teacher jsonb;
    v_room_id UUID;
    v_owner   UUID;
    v_student jsonb;
    v_count   INT;
    v_msg_id  UUID;
BEGIN
    -- ---------- Room 1: CSE 2k23 Batch (created by teacher 1) ----------
    SELECT (t->>'uid')::UUID INTO v_owner
    FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'teachers') t
    WHERE t->>'employee_id' = 'EMP-101';

    INSERT INTO public.chat_room (type, title, room_code, is_ephemeral, created_by)
    VALUES ('group', 'CSE 2k23 Batch', 'CSE23BATCH', FALSE, v_owner)
    ON CONFLICT (room_code) DO NOTHING
    RETURNING id INTO v_room_id;

    IF v_room_id IS NULL THEN
        SELECT id INTO v_room_id FROM public.chat_room WHERE room_code = 'CSE23BATCH';
    END IF;

    IF v_room_id IS NOT NULL THEN
        INSERT INTO public.chat_room_member (room_id, profile_id, member_role)
        VALUES (v_room_id, v_owner, 'owner')
        ON CONFLICT (room_id, profile_id) DO NOTHING;

        v_count := 0;
        FOR v_student IN
            SELECT * FROM jsonb_array_elements(
                current_setting('seed.ids', true)::jsonb->'students'
            )
        LOOP
            EXIT WHEN v_count >= 10;
            INSERT INTO public.chat_room_member (room_id, profile_id, member_role)
            VALUES (v_room_id, (v_student->>'uid')::UUID, 'member')
            ON CONFLICT (room_id, profile_id) DO NOTHING;
            v_count := v_count + 1;
        END LOOP;

        INSERT INTO public.chat_message (room_id, sender_id, body)
        VALUES (v_room_id, v_owner, 'Welcome to the CSE 2k23 batch group!');

        INSERT INTO public.chat_message (room_id, sender_id, body)
        SELECT v_room_id, (t->>'uid')::UUID, 'Thanks for setting this up, sir!'
        FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'students') t
        WHERE t->>'roll' = '2023715001';

        INSERT INTO public.chat_message (room_id, sender_id, body)
        VALUES (v_room_id,
                (SELECT (t->>'uid')::UUID FROM jsonb_array_elements(
                    current_setting('seed.ids', true)::jsonb->'students') t
                 WHERE t->>'roll' = '2023715002'),
                'Lab report submission deadline?');
    END IF;

    -- ---------- Room 2: CSE Faculty Lounge (created by teacher 4) ----------
    SELECT (t->>'uid')::UUID INTO v_owner
    FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'teachers') t
    WHERE t->>'employee_id' = 'EMP-104';

    INSERT INTO public.chat_room (type, title, room_code, is_ephemeral, created_by)
    VALUES ('group', 'CSE Faculty Lounge', 'CSEDU-FAC', FALSE, v_owner)
    ON CONFLICT (room_code) DO NOTHING
    RETURNING id INTO v_room_id;

    IF v_room_id IS NULL THEN
        SELECT id INTO v_room_id FROM public.chat_room WHERE room_code = 'CSEDU-FAC';
    END IF;

    IF v_room_id IS NOT NULL THEN
        INSERT INTO public.chat_room_member (room_id, profile_id, member_role)
        SELECT v_room_id, (t->>'uid')::UUID, 'member'
        FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'teachers') t
        WHERE t->>'employee_id' IN ('EMP-101','EMP-102','EMP-103','EMP-104','EMP-105')
        ON CONFLICT (room_id, profile_id) DO NOTHING;

        UPDATE public.chat_room_member
        SET member_role = 'owner'
        WHERE room_id = v_room_id AND profile_id = v_owner;

        INSERT INTO public.chat_message (room_id, sender_id, body)
        VALUES (v_room_id, v_owner, 'Reminder: faculty meeting Friday at 3pm.');
    END IF;

    -- ---------- Room 3: Project Team Alpha (password-protected, ephemeral) ----------
    SELECT (t->>'uid')::UUID INTO v_owner
    FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'teachers') t
    WHERE t->>'employee_id' = 'EMP-102';

    INSERT INTO public.chat_room (type, title, room_code, password_hash, is_ephemeral, created_by)
    VALUES (
        'group', 'Project Team Alpha', 'PROJTEAM01',
        extensions.crypt('demo1234', extensions.gen_salt('bf')),
        TRUE, v_owner
    )
    ON CONFLICT (room_code) DO NOTHING
    RETURNING id INTO v_room_id;

    IF v_room_id IS NULL THEN
        SELECT id INTO v_room_id FROM public.chat_room WHERE room_code = 'PROJTEAM01';
    END IF;

    IF v_room_id IS NOT NULL THEN
        INSERT INTO public.chat_room_member (room_id, profile_id, member_role)
        VALUES (v_room_id, v_owner, 'owner')
        ON CONFLICT (room_id, profile_id) DO NOTHING;

        INSERT INTO public.chat_room_member (room_id, profile_id, member_role)
        SELECT v_room_id, (t->>'uid')::UUID, 'member'
        FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'students') t
        WHERE t->>'roll' IN ('2023715001','2023715002','2023715003','2023715004','2023715005')
        ON CONFLICT (room_id, profile_id) DO NOTHING;

        INSERT INTO public.chat_message (room_id, sender_id, body)
        VALUES (v_room_id, v_owner, 'Standup tomorrow at 11am.');
    END IF;

    -- ---------- 1 pending chat_request ----------
    -- No unique constraint on (from_id, to_id) exists, so guard idempotency
    -- with an explicit existence check instead of ON CONFLICT.
    INSERT INTO public.chat_request (from_id, to_id, status, room_title)
    SELECT (s->>'uid')::UUID,
           (t->>'uid')::UUID,
           'pending',
           'Hi, I had a question about the assignment'
    FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'students') s
    CROSS JOIN jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'teachers') t
    WHERE s->>'roll' = '2023715010' AND t->>'employee_id' = 'EMP-101'
      AND NOT EXISTS (
          SELECT 1 FROM public.chat_request cr
          WHERE cr.from_id = (s->>'uid')::UUID AND cr.to_id = (t->>'uid')::UUID
      );
END $$;


-- =====================================================================
-- J. Notifications (8 sample rows so the bell icon is non-empty)
-- =====================================================================
INSERT INTO public.notification (recipient_id, sender_id, notif_type, title, body, is_read)
SELECT
    (t->>'uid')::UUID,
    (s->>'uid')::UUID,
    'new_project',
    'New project published',
    COALESCE((SELECT title FROM public.project WHERE user_id = (s->>'uid')::UUID ORDER BY created_at DESC LIMIT 1),
             'A new project was added'),
    FALSE
FROM jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'teachers') t,
     jsonb_array_elements(current_setting('seed.ids', true)::jsonb->'students') s
WHERE s->>'roll' IN ('2023715001','2023715002','2023715003','2023715004','2023715005',
                     '2023715006','2023715007','2023715008');


-- =====================================================================
-- K. Refresh sequence values so the next API insert is unaffected
-- =====================================================================
SELECT setval('public.manual_course_manual_course_id_seq',
              GREATEST((SELECT COALESCE(MAX(manual_course_id), 1) FROM public.manual_course), 1));
SELECT setval('public.manual_enrollment_enrollment_id_seq',
              GREATEST((SELECT COALESCE(MAX(enrollment_id), 1) FROM public.manual_enrollment), 1));
SELECT setval('public.course_invite_invite_id_seq',
              GREATEST((SELECT COALESCE(MAX(invite_id), 1) FROM public.course_invite), 1));
SELECT setval('public.project_project_id_seq',
              GREATEST((SELECT COALESCE(MAX(project_id), 1) FROM public.project), 1));
SELECT setval('public.certificate_certificate_id_seq',
              GREATEST((SELECT COALESCE(MAX(certificate_id), 1) FROM public.certificate), 1));
SELECT setval('public.research_paper_paper_id_seq',
              GREATEST((SELECT COALESCE(MAX(paper_id), 1) FROM public.research_paper), 1));
SELECT setval('public.advisor_id_seq',
              GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.advisor), 1));
SELECT setval('public.notification_notification_id_seq',
              GREATEST((SELECT COALESCE(MAX(notification_id), 1) FROM public.notification), 1));
SELECT setval('public.attendance_session_session_id_seq',
              GREATEST((SELECT COALESCE(MAX(session_id), 1) FROM public.attendance_session), 1));
SELECT setval('public.attendance_record_record_id_seq',
              GREATEST((SELECT COALESCE(MAX(record_id), 1) FROM public.attendance_record), 1));
SELECT setval('public.exam_exam_id_seq',
              GREATEST((SELECT COALESCE(MAX(exam_id), 1) FROM public.exam), 1));
SELECT setval('public.exam_mark_mark_id_seq',
              GREATEST((SELECT COALESCE(MAX(mark_id), 1) FROM public.exam_mark), 1));


-- =====================================================================
-- L. Summary
-- =====================================================================
DO $$
DECLARE
    v_students    INT;
    v_instructors INT;
    v_courses     INT;
    v_enrolls     INT;
    v_invites     INT;
    v_projects    INT;
    v_certs       INT;
    v_papers      INT;
    v_advisors    INT;
    v_rooms       INT;
    v_sessions    INT;
    v_exams       INT;
BEGIN
    SELECT COUNT(*) INTO v_students    FROM public.student;
    SELECT COUNT(*) INTO v_instructors FROM public.instructor;
    SELECT COUNT(*) INTO v_courses     FROM public.manual_course;
    SELECT COUNT(*) INTO v_enrolls     FROM public.manual_enrollment;
    SELECT COUNT(*) INTO v_invites     FROM public.course_invite;
    SELECT COUNT(*) INTO v_projects    FROM public.project;
    SELECT COUNT(*) INTO v_certs       FROM public.certificate;
    SELECT COUNT(*) INTO v_papers      FROM public.research_paper;
    SELECT COUNT(*) INTO v_advisors    FROM public.advisor WHERE student_id IS NOT NULL;
    SELECT COUNT(*) INTO v_rooms       FROM public.chat_room WHERE type = 'group';
    SELECT COUNT(*) INTO v_sessions    FROM public.attendance_session;
    SELECT COUNT(*) INTO v_exams       FROM public.exam;

    RAISE NOTICE '============================================================';
    RAISE NOTICE 'Seed complete.';
    RAISE NOTICE '  students:    %', v_students;
    RAISE NOTICE '  instructors: %', v_instructors;
    RAISE NOTICE '  courses:     %', v_courses;
    RAISE NOTICE '  enrollments: %', v_enrolls;
    RAISE NOTICE '  invites:     %', v_invites;
    RAISE NOTICE '  projects:    %', v_projects;
    RAISE NOTICE '  certificates:%', v_certs;
    RAISE NOTICE '  papers:      %', v_papers;
    RAISE NOTICE '  advisors:    %', v_advisors;
    RAISE NOTICE '  group rooms: %', v_rooms;
    RAISE NOTICE '  attendance sessions: %', v_sessions;
    RAISE NOTICE '  exams:       %', v_exams;
    RAISE NOTICE '============================================================';
END $$;
